export const CAR_TYPES = {
  CAR_FETCHING_START: "CAR_FETCHING_START",
  CAR_FETCHING_SUCCESS: "CAR_FETCHING_SUCCESS",
  CAR_FETCHING_FAILED: "CAR_FETCHING_FAILED",
  CAR_POST_START: "CAR_POST_START",
  CAR_POST_SUCCESS: "CAR_POST_SUCCESS",
  CAR_POST_FAILED: "CAR_POST_FAILED",
  CAR_PUT_START: "CAR_PUT_START",
  CAR_PUT_SUCCESS: "CAR_PUT_SUCCESS",
  CAR_PUT_FAILED: "CAR_PUT_FAILED",
  CAR_DELETE_START: "CAR_DELETE_START",
  CAR_DELETE_SUCCESS: "CAR_DELETE_SUCCESS",
  CAR_DELETE_FAILED: "CAR_DELETE_FAILED",
};
